'''file=open("file1.txt","x")
file.close()'''
file=open("file1.txt","w")
#writing into a file using write()
file.write("hello world\n")
file.write("how are you ?\n")
#writing into a file using writelines()
file.writelines(["this is line1\n","this is line2\n","this is line3"])
file.close()
file=open("file1.txt","r")
print("reading a file using read():")
print(file.read())
file.close()
file=open("file1.txt","r")
print("reading a file using readline():")
print(file.readline(7))
file.close()
file=open("file1.txt","r")
print("reading a file using readlines():")
print(file.readlines())

